config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'
  root 'pages#one'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Actividad21</title>
    <%= csrf_meta_tags %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item">
            <a class="nav-link" href="<%= root_path %>">One</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= pages_two_path %>">Two</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= pages_three_path %>">Three</a>
          </li>
      </div>
    </nav>
    <!-- Fin Navbar -->
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/one.html.erb
<h2 class="text-info">Pages#one</h2>
<p>Find me in app/views/pages/one.html.erb</p>

<h1>Javier COlihuinca :v</h1>


<%= image_tag 'meme-02.jpg', alt: 'meme pacman', class: 'rounded mx-auto d-block img-fluid' %>

app/views/pages/three.html.erb
<h2 class="text-info">Pages#three</h2>
<p>Find me in app/views/pages/three.html.erb</p>

<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ab nesciunt, voluptatem, earum maiores aliquam maxime aut eum incidunt eius enim in optio, reprehenderit eaque!</p>

<%= image_tag 'meme-01.jpg', alt: 'meme mono', class: 'rounded mx-auto d-block img-fluid' %>

app/views/pages/two.html.erb
<h2 class="text-info">Pages#two</h2>
<p>Find me in app/views/pages/two.html.erb</p>

<%= image_tag "image-routes.png", alt: "Rails routes", class: 'rounded mx-auto d-block img-fluid' %>